레논 깃 서치 예제
koba0909/AndroidStudy pull request #6
Opened 2021-04-06 09:01 UTC by Lee-cg

깃 서치 예제 완성했습니다.

2021-04-06 10:44 UTC, koba0909 requested changes
리뷰 확인부탁드립니다~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +internal class AuthInterceptor(private val token: String) : Interceptor {
요거 inner클래스로 지정안해줘도 될거 같은데 inner class로 지정한 이유가 있을까요?

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +        .baseUrl("https://github.com/")
이 프로젝트에선 api를 2개밖에 사용 안하는데 보통 url를 const로 지정해주고 사용합니다.

이렇게 하는 이유엔 2가지 정도 이점이 있어요
- 추후 base url 변경시 수정이 편리하다.
- 내부적으로 .baseUrl()을 할때 마다 string 객체를 반복적으로 만드는것을 방지할 수 있다.
```kotlin
companion object {
const val BASE_GITHUB_URL = "https://github.com/"
const val BASE_API_GITHUB_URL = "https://api.github.com/"
}

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +                    addHeader("Authorization", "token $token")
Authorization 도 companion object로 뺄 수 있을거 같아요

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubAccessToken.kt
> +class GithubAccessToken(@field:SerializedName("access_token") val accessToken: String, val scope: String, @field:SerializedName("token_type") val tokenType: String)
이거 data class로 만들지 않은 이유가 있을까요?
아래와 같이 개행하면 가독성에 더욱 좋습니다.

```kotlin
data class GithubAccessToken(
    @field:SerializedName("access_token") 
    val accessToken: String, 
    val scope: String, 
    @field:SerializedName("token_type") 
    val tokenType: String
)
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubOwner.kt
> +class GithubOwner(val login: String, @field:SerializedName("avatar_url") val avatarUrl: String)
GithubAccessToken에 남긴 코멘트처럼 data class로 변경 및 개행하면 더 좋을거 같아요

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubRepo.kt
> +class GithubRepo(val name: String,
GithubAccessToken에 남긴 코멘트처럼 data class로 변경 및 개행하면 더 좋을거 같아요

+ Repo라는 이름이 Repository랑 헷갈려서 다른 이름 클래스명 수정하면 좋을거 같아요

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/RepoSearchResponse.kt
> +class RepoSearchResponse(
GithubAccessToken에 남긴 코멘트처럼 data class로 변경 및 개행하면 더 좋을거 같아요

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/data/AuthTokenProvider.kt
> +    val token: String?
변수는 함수보다 위에 선언해주는게 좋습니다~

외부에서 token값 변경이 불가하도록 private를 붙여주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/SimpleGithubGlideModule.kt
> +class SimpleGithubGlideModule : AppGlideModule() { // Intentionally left blank
이건 사용하는곳이 없는 클래스인가요?

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/main/MainActivity.kt
> +        btnSearch = findViewById(R.id.btnActivityMainSearch)
ViewBinding 이나 DataBinding을 통해 findViewById없이 객체 선언이 가능하도록 수정이 필요해요

findViewById는 레이아웃 중첩이 있을시 많은 성능 저하를 불러옵니다.

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/main/MainActivity.kt
> +        btnSearch.setOnClickListener(View.OnClickListener { startActivity(Intent(this@MainActivity, SearchActivity::class.java)) })
아래와 같이 수정하면 가독성이 더 좋을거 같아 제안드립니다~
```suggestion
btnSearch.setOnClickListener{ goToSearch() }

fun goToSearch() =
​startActivity(Intent(this, SearchActivity::class.java))
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +        llContent = findViewById(R.id.llActivityRepositoryContent)
findVIewById 없애주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    val dateFormatInResponse = SimpleDateFormat(
GithubApi 처럼 by lazy로 선언해주는건 어떤가요?

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    internal lateinit var llContent: LinearLayout
internal이 사용되어야 하나요?

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    internal var repoCall: Call<GithubRepo>? = null
repoCall을 by lazy로 선언해줄 수 있을거 같아요

login과 repoName이 없으면 exception을 throw 해주고 있는데 이러면 
앱이 죽어버립니다.

아래와 같이 activity에서 init시에 이를 체크하고 액티비트를 종료하는 등 crash방지 로직이 필요한거 같아요. 
```kotlin
val repoCall: Call<GithubRepo> by lazy { api.getRepository(login, repoName) }

val login by lazy { intent?.getStringExtra(KEY_USER_LOGIN) ?: "" }
val repo by lazy { intent?.getStringExtra(KEY_REPO_NAME) ?:  "" }

init {
    // login과 repo가 empty이면 액티비티 종료 등의 로직 필요
}
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +        repoCall!!.enqueue(object : Callback<GithubRepo?> {
repoCall을 lazy하게 선언해주면 !!은 제거 가능할거에요

!!은 exception을 불러일으켜서 사용하지 않는게 좋습니다.

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +                    if (null == repo.description) {
약간 코드가 자바스러운거 같아서 아래와 같이 수정 제안 해봅니다~( 취향의 영역이긴 합니다)

그리고 String은 null체크보단  isNullOrBlank혹은 isNullOrEmpty를 활용하면  
null 뿐만아니라 ""(empty) 혹은 "  "(blank) 이런 형태도 체크할 수 있어 활용하시면 좋을거 같아요~

```kotilin
tvDescription.text = if(description.isNullOrBlank()) {
    getString(R.string.no_description_provided)
}else {
    repo.description
}
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +                    showError("Not successful: " + response.message())
코틀린에선 아래와 같이 사용하는걸 추천드립니다~
```
showError("Not successful: ${response.message()}")
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    private fun showRepositoryInfo(login: String, repoName: String) {
이 로직은 뷰모델안에서 실행하고 액티비티에서 라이브데이터를 옵저빙하는 방식으로  
구성하면 비즈니스로직을 뷰모델에게 넘길 수 있어서 추천드립니다~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    internal lateinit var rvList: RecyclerView
여기도 internal로 선언되어 있네요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    internal var searchCall: Call<RepoSearchResponse>? = null
by lazy로 선언 가능할거 같아요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                    if (""==searchView.query) {
searchView.query.isEmpty()로 대체 가능합니다~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +            override fun onResponse(call: Call<RepoSearchResponse>,
searchCall을 by lazy로 선언해주고 !! 제거해주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                if (response.isSuccessful && null != searchResult) {
조건을 여러개 줄땐 개행을 하면 가독성에 조금 더 좋습니다~
```
 if (response.isSuccessful 
        && null != searchResult) {
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                        with(adapter) {
adapter안에 updateItems같은 함수를 만들어서 아래 로직을 처리하는게 좋을거 같아요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    private fun clearResults() {
이로직은 adapter안에 선언해놓고 사용하는게 좋아보여요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +        supportActionBar?.run{
run스코프를 사용하신 이유가 있을까요?

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    private fun hideSoftKeyboard() {
소프트키보드를 show, hide 를 시키는 로직은 다른 액티비티나 프래그먼트에서 사용할 수 있기 때문에 유틸클래스나 코틀린 익스텐션 함수로 지정해 놓고 사용하는게 좋습니다~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +        items[position].let { repo ->
onBindViewHolder안에서 뷰바인드를 직접해주고 있는데 ViewHolder에서 처리하게 하는게 좋을거 같아요.

지금 예제에선 ViewHolder가 하나이지만 뷰홀더가 여러개가 될 수도 있고 bindViewHolder에선 뷰홀더에 뷰를 바인드해야한다는 로직만 들고 있는게 좋습니다~

 KobaTodo/TodoAdapter.kt를 참고하시면 좋을거 같아요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +                setOnClickListener {
뷰를 바인드해주는곳에서 setOnClickListenr를 해주는건 성능저하를 불러옵니다~

클릭리스너를 세팅해주는건 뷰홀더를 생성할때만 들어가면 되기 때문에 보통 ViewHolder를 init할때 넣어줍니다


TodoViewHolder참고해주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +    private var listener: ItemClickListener? = null
클릭 리스너를 받아서 사용하고 있는데 클릭 관련된 subject를 만들어서 activity에서 구독하고 있으면
리스너를 넘기지 않도록 처리 가능합니다~

TodoAdapter의 clickSubject를 참고해주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        btnStart = findViewById(R.id.btnActivitySignInStart)
뷰바인딩이 사용 안되었어요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +            val intent = CustomTabsIntent.Builder().build()
스코프사용을 하는 이유중에 하나는 변수선언을 줄일 수 있어서 입니다~

 아래와 같이 제안드려봅니다~

```kotlin
CustomTabsIntent.Builder().build().run{
    this.launchUrl(this@SignInActivity, authUri)
}
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +            val authUri = Uri.Builder().scheme("https").authority("github.com")
이렇게 복잡하게 Uri를 만들 이유가 없는거 같아요
아래처럼 Uri.parse사용 하는 방식으로 수정 제안드립니다~
```
val authUri = Uri.parse("https://github.com/login/oauth/authorize?client_id=${BuildConfig.GITHUB_CLIENT_ID}")
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        val uri = intent.data ?: throw IllegalArgumentException("No data exists")
IllegalArgumentException을 던지면 이를 캐치해서 예외처리하는 try catch가 필요해요 아니면 앱이 죽습니다~

data가 없을 경우 throw exception이 아닌 다른 처리가 필요해요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        accessTokenCall!!.enqueue(object : Callback<GithubAccessToken?> {
RepositoryActivity에서 코멘트 드린 것처럼 by lazy로 선언한다면 !!를 사용하지 않을 수 있어요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +                if (response.isSuccessful && null != token) {
조건 개행 해주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +                            "Not successful: " + response.message()))
"Not successful: " + response.message() ->
"Not successful: ${response.message()}"

로 수정해주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        startActivity(Intent(
아래와 같이 수정 제안드립니다~
```suggestion
        startActivity(
            Intent(this, MainActivity::class.java).apply {
                addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
        )
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RepositoryHolder =
보통 뷰홀더에 parent를 보다 여기서 레이아웃을 inflate 해서 넘겨줍니다~

```suggestion 
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RepositoryHolder {
    val view = LayoutInflater.from(parent.context).inflate(R.layout.item_repository, parent, false)
    return RepositoryHolder(view)
}
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +    class RepositoryHolder(parent: ViewGroup) : RecyclerView.ViewHolder(LayoutInflater.from(parent.context)
onCreateView에서 view를 넘겨주면 아래처럼 수정 가능합니다~

```suggestion
class RepositoryHolder(view: View) : RecyclerView.ViewHolder(view)
```

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +            ivProfile = itemView.findViewById(R.id.ivItemRepositoryProfile)
뷰바인딩이나 데이터바인딩으로 findViewById 없애주세요~

2021-04-06 10:44 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/res/layout/activity_repository.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
RelativeLayout은 inflate될때 ConstraintLayout보다 속도가 느립니다~ 

ConstraintLayout을 사용하시는걸 추천드립니다

2021-04-06 11:37 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RepositoryHolder =
뷰바인딩을 사용한다면 바인딩을 넘겨줍니다~

```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RepositoryHolder {
   val binding = ItemRepositoryBinding.inflate(
            LayoutInflater.from(parent.context),
            parent,
            false
)
    return RepositoryHolder(binding)
}

```

2021-04-06 11:40 UTC, koba0909 reviewed
이것도 확인해주세요~

2021-04-06 11:40 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +    class RepositoryHolder(parent: ViewGroup) : RecyclerView.ViewHolder(LayoutInflater.from(parent.context)
onCreateView에서 binding를 넘겨주면 아래처럼 수정 가능합니다~

```suggestion
class RepositoryHolder(binding: ItemRepositoryBinding) : RecyclerView.ViewHolder(binding.root)
```

2021-04-07 06:23 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +internal class AuthInterceptor(private val token: String) : Interceptor {
같은 패지지(package com.androidhuman.example.simplegithub.api)에서 사용할 수 있도록 internal 키워드를 사용했습니다.
해당 클래스는 현재 GithubApiProvider.kt 내에서만 사용되고 있습니다.

2021-04-07 06:29 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +        .baseUrl("https://github.com/")
GithubApiProvider.kt은 클래스없이 top-level 함수로 정의되어 있는데 클래스 없이 companion object를 사용하는 방법이 있을까요?

2021-04-07 06:30 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +                    addHeader("Authorization", "token $token")
GithubApiProvider.kt은 클래스없이 top-level 함수로 정의되어 있는데 클래스 없이 companion object를 사용하는 방법이 있을까요?

2021-04-07 06:47 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubAccessToken.kt
> +class GithubAccessToken(@field:SerializedName("access_token") val accessToken: String, val scope: String, @field:SerializedName("token_type") val tokenType: String)
data 클래스를 명시해주는게 좋겠군요. 감사합니다.

2021-04-07 06:47 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubOwner.kt
> +class GithubOwner(val login: String, @field:SerializedName("avatar_url") val avatarUrl: String)
data 클래스를 명시해주는게 좋겠군요. 감사합니다.

2021-04-07 06:54 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +internal class AuthInterceptor(private val token: String) : Interceptor {
저도 같은 클래스내에서 사용하기 위해 inner class를 사용하곤 했는데 이거가 좋지 않다고 하네요. out로 직접 접근하는 방식은 추후 문제가 발생할 수 있다고 합니다. 

[https://git.afreecatv.com/MobileAndroid/afreecatv/-/merge_requests/151#note_44847](https://git.afreecatv.com/MobileAndroid/afreecatv/-/merge_requests/151#note_44850)
[https://git.afreecatv.com/MobileAndroid/afreecatv/-/merge_requests/151#note_44850](https://git.afreecatv.com/MobileAndroid/afreecatv/-/merge_requests/151#note_44850)
깃랩에서 관련해서 논의된 mr 남깁니다~

2021-04-07 06:55 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +        .baseUrl("https://github.com/")
아 그렇군여 그렇담 const val 로만 지정해주면 됩니다~

```suggestion
const val BASE_GITHUB_URL = "https://github.com/"
const val BASE_API_GITHUB_URL = "https://api.github.com/"
```

2021-04-07 06:55 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +                    addHeader("Authorization", "token $token")
이것도 const val로만 지정해주세요~

2021-04-07 07:09 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        startActivity(Intent(
apply로 수정하겠습니다.

2021-04-07 08:03 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RepositoryHolder =
뷰바인딩 사용해보겠습니다.

2021-04-07 08:05 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +    class RepositoryHolder(parent: ViewGroup) : RecyclerView.ViewHolder(LayoutInflater.from(parent.context)
뷰바인딩으로 사용해보겠습니다.

2021-04-07 09:21 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +internal class AuthInterceptor(private val token: String) : Interceptor {
internal클래스이네요 resolve하겠습니다~

2021-04-09 04:59 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +            ivProfile = itemView.findViewById(R.id.ivItemRepositoryProfile)
뷰바인딩 사용완료!

2021-04-16 03:03 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +        .baseUrl("https://github.com/")
수정 완료!

2021-04-16 03:04 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/GithubApiProvider.kt
> +                    addHeader("Authorization", "token $token")
수정 완료!

2021-04-16 03:09 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubRepo.kt
> +class GithubRepo(val name: String,
data class 변경 완료!
Repo가 의미하는게 깃헙 Repository가 아닌가욥??

2021-04-16 03:10 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/RepoSearchResponse.kt
> +class RepoSearchResponse(
data class 변경 완료!

2021-04-16 03:36 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/data/AuthTokenProvider.kt
> +    val token: String?
변수를 함수 위에 선언해주었습니다.
token 프로퍼티에 private 키워드를 넣으면 getter와 setter가 생성되지가 않네요.
token을 GitHubApiProvider.kt랑 SignInActivity.kt에서 쓰고 있기 때문에 private 키워드를 붙이지 않았습니다.

2021-04-16 05:13 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/main/MainActivity.kt
> +        btnSearch = findViewById(R.id.btnActivityMainSearch)
MainActivity쪽 뷰바인딩 적용했습니다.

2021-04-16 05:18 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/main/MainActivity.kt
> +        btnSearch.setOnClickListener(View.OnClickListener { startActivity(Intent(this@MainActivity, SearchActivity::class.java)) })
startActivity 함수는 Activity에 있는 함수로 goToSearch함수에 패러미터로 Activity를 넘겨줘야 할 것 같습니다. 그래서 개인적으로 코드가 좀 길어보이는데, `        btnSearch.setOnClickListener {
            startActivity(Intent(this, SearchActivity::class.java)) }`로 수정하는건 어떨까요?

2021-04-16 05:20 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +        llContent = findViewById(R.id.llActivityRepositoryContent)
뷰바인딩 적용 완료!

2021-04-16 05:26 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    val dateFormatInResponse = SimpleDateFormat(
뷰바인딩 적용으로 tvMessage 프로퍼티 삭제

2021-04-16 05:27 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    internal lateinit var llContent: LinearLayout
뷰바인딩으로 llContnet 프로퍼티 삭제

2021-04-16 05:36 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    internal var repoCall: Call<GithubRepo>? = null
널러블 타입보다는 by lazy가 더 안전하겠군요. 
repoCall 프로퍼티는 rxJava를 적용하면서 삭제했습니다.

2021-04-16 05:37 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +        repoCall!!.enqueue(object : Callback<GithubRepo?> {
!!지양하기 메모 메모..

2021-04-16 05:50 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +                    if (null == repo.description) {
코틀린을 코틀린스럽게 하는것도 중요하다 생각합니다. ㅎㅎㅎ

2021-04-16 06:07 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +                    showError("Not successful: " + response.message())
문자열 템플릿 적용!

2021-04-16 06:09 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/repo/RepositoryActivity.kt
> +    private fun showRepositoryInfo(login: String, repoName: String) {
Rx자바를 적용해봤습니다. Rx를 처음 공부할때 LiveData 패턴이랑 비슷해서 공부하기고 조금 수월했습니다.

2021-04-16 06:10 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    internal lateinit var rvList: RecyclerView
뷰바인딩으로 rvList 프로퍼티 삭제!

2021-04-16 06:23 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    internal var searchCall: Call<RepoSearchResponse>? = null
rx자바 적용으로 searchCall 프로퍼티 삭제

2021-04-16 06:25 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                    if (""==searchView.query) {
isEmpty()로 수정!

2021-04-16 06:26 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +            override fun onResponse(call: Call<RepoSearchResponse>,
Rx자바 적용으로로 해당 코드는 삭제했습니다~

2021-04-16 06:27 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                if (response.isSuccessful && null != searchResult) {
가독성을 위해 개행하겠습니다.

2021-04-16 06:33 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                        with(adapter) {
adapter안에 `    fun updateItem(items: List<GithubRepo>) {
         setItems(items)
         notifyDataSetChanged()
     }` 함수를 만들어서 적용했습니다.

2021-04-16 06:38 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    private fun clearResults() {
adapter안에 `    fun clearResults() {
        clearItems()
        notifyDataSetChanged()
    }` 함수를 만들어서 적용했습니다.

2021-04-16 06:47 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +        supportActionBar?.run{
단순히 ActionBar의 타이틀을 바꾸는 용도로 사용했습니다. 한줄 코드를 run 스코프로 쓰는게 좀 그런가용???

2021-04-16 07:00 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +    private fun hideSoftKeyboard() {
Util파일을 새로만들어서 
```
    fun hideSoftKeyboard(activity: AppCompatActivity, view: View) {
    (activity.getSystemService(AppCompatActivity.INPUT_METHOD_SERVICE) as InputMethodManager).run {
        hideSoftInputFromWindow(view.windowToken, 0)
    }
}
``` 

`hideSoftKeyboard(this@SearchActivity, searchView)`이렇게 적용했습니다!

2021-04-16 09:07 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +                setOnClickListener {
ViewHoder에 클릭리스너를 달기위해서는 adpater에 있는 listenr와 item 리스트를 가져와야합니다.
ViewHoder에서 adapter에 있는 listener와 item 리스트를 가져오기위해서 adpater 안에 있는 ViewHoder를 inner 클래스로 정의하거나 ViewHolder의 생성자 파라미터에 linster와 item을 전달받을 수 밖에 없는데 더 좋은 방법이 있을까요?

2021-04-16 09:12 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +        items[position].let { repo ->
bind 메소드를 ViewHolder에 정의하고, onBindViewHolder에서 사용하는게 맞나요?

2021-04-16 09:12 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        btnStart = findViewById(R.id.btnActivitySignInStart)
뷰바인딩 사용!

2021-04-16 09:14 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +            val intent = CustomTabsIntent.Builder().build()
run을 쓰니 val intent 변수가 필요가 없어지군요.

2021-04-16 09:17 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +            val authUri = Uri.Builder().scheme("https").authority("github.com")
수정했습니당~

2021-04-16 09:18 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        accessTokenCall!!.enqueue(object : Callback<GithubAccessToken?> {
accessTokenCall 프로퍼티 삭제하였습니다.

2021-04-16 09:18 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +                if (response.isSuccessful && null != token) {
확인!

2021-04-16 09:18 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +                            "Not successful: " + response.message()))
확인!

2021-04-21 04:52 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubRepo.kt
> +class GithubRepo(val name: String,
깃헙의 Repositroy  랑 아키텍처에서 사용하는 Repository  랑 이름이 같아 제안드린거였어요~

2021-04-21 04:58 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/main/MainActivity.kt
> +        btnSearch.setOnClickListener(View.OnClickListener { startActivity(Intent(this@MainActivity, SearchActivity::class.java)) })
goToSearch 가 Activity 안에서만 실행되서 파라미터로 안넘겨줘도 됩니다~

레논말처럼 한줄로 표현되는 코드이기에 별도의 함수로 안빼도 되는데 저는 한줄이라도 함수 네이밍으로 해당 코드의 목적, 행동을 명시하는걸 선호해서 제안 드렸습니다~.

2021-04-21 05:03 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +        supportActionBar?.run{
제생각엔 오히려 가독성을 해치는거 같아요~

2021-04-21 05:05 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +        items[position].let { repo ->
네~ 추후 뷰타입을 정의하여 여러개의 뷰홀더를 사용해야 하는데 그러면  onBindViewHolder 내부에서 뷰홀더 타입체크가 이루어 지게 됩니다. 조건문을 사용하는건 가능하면 지양해야하는 코드입니다. onBindViewHolder에선 뷰홀더로 바인드 여부만 넘기고 실제적인 바인드는 뷰홀더 안에서 이루어지는게 맞을거 같아요.

2021-04-21 05:13 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +                setOnClickListener {
1. 뷰홀더에서  adapterPosition 만 넘기고 받아 쓰는 곳에서 adapter 의 item[adapterPosition]을 사용하는 방법

2. 뷰홀더의  outer 클래스를 넘기거나 item을 생성자로 넘겨 클릭리스너에 item[adapterPosition]을 넘기는 방법

레논이 생각한것처럼 위의 두가지 방법이 있을거 같아요. 어떤 방식을 사용해도 괜찮을거 같습니다. bind 안에서 setClickListener를 해주는건 꼭 하지말아야 합니다.

2021-04-21 05:30 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                .subscribe())
subscribe()에서 하는일이 없는데 rx으로 변환한 이유가 있을까요?

2021-04-21 05:30 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +        startActivity(intent)
onItemClick에서 지금 두가지 일을 하고 있습니다~ 이럴땐 함수로 묶어주면 가독성에 도움이 됩니다.
(함수명은 자유입니다.)

``` 
onItemClick(){
saveSearchKeyword()
goToRepositoryActivity()
}
```

2021-04-21 05:30 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                    }
with스코프가 쓰인 이유가 있을까요??

2021-04-21 05:30 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                    }
여기도 with 스코프가 사용되었네요

2021-04-27 07:45 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/api/model/GithubRepo.kt
> +class GithubRepo(val name: String,
GithubRepoDto로 변경했습니다.

2021-04-27 08:46 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/SimpleGithubGlideModule.kt
> +class SimpleGithubGlideModule : AppGlideModule() { // Intentionally left blank
@GlideModule 어노테이션을 작성하고 AppGildeModule()을 상속하는 커스텀 Glide 클래스를 작성하면 `Glide.with() `대신 `GildeApp.with()`으로 글라이드 라이브러리를 호출할 수 있습니다.

이것은 Gilde v4에서 생긴 Generated API라는 개념인데 Generated API의 장점은 커스텀 옵션과 함께 Gilde의 API를 확장할 수 있고, Glide API에 자주 사용되는 옵션을 번들로 묶어서 메소드로 추가할 수 있습니다.

실제 사용된 예로 SearchAdapter.kt에서 사용되는데,
```
    GlideApp.with(context)
     .load(repo.owner.avatarUrl)
     .placeholder(placeholder)
     .into(holder.binding.ivItemRepositoryProfile)
```

Generated API를 쓰지 않고 기존처름 그냥 Glide를 사용하면
```
Glide.with(context)
        .load(repo.owner.avatarUrl)
        .apply(RequestOptions()
                .placeholder(placeholder)
        ).into(holder.binding.ivItemRepositoryProfile)
```
이렇게 사용할 수 있습니다.

자세한 내용은 https://bumptech.github.io/glide/doc/generatedapi.html에 있습니다.

2021-04-27 08:55 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/main/MainActivity.kt
> +        btnSearch.setOnClickListener(View.OnClickListener { startActivity(Intent(this@MainActivity, SearchActivity::class.java)) })
goToSearch()가  Activity에서 실행되므로 그냥 startActivity가 호출이 되군요. 

제가 생각하는 함수를 만드는 철학은 `재활용이 되는가?`였습니다. 한곳에서만 쓰이는 코드이거나 어떻게 돌아가는지 한눈에 보이는 코드는 굳이 함수를 만들지 말자는 게 제 코딩 철학? 이 었는데, 휴 말씀처럼 한 번만 쓰이는 코드라도 협업하는 입장에서 명시적으로 어떤 동작을 하는지 함수를 만들어 작성하는 것도 좋아 보이네요.

2021-04-27 09:00 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +        supportActionBar?.run{
`        supportActionBar?.subtitle = query`로 수정하였습니다.

2021-04-27 12:54 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/SimpleGithubGlideModule.kt
> +class SimpleGithubGlideModule : AppGlideModule() { // Intentionally left blank
placeholder는 glide에서 제공을 해주긴 합니다. 
[https://bumptech.github.io/glide/doc/placeholders.html](https://bumptech.github.io/glide/doc/placeholders.html)

옵션을 번들로 묶어서 메소드를 추가할 수 있군여 여러 옵션을 사용해할때 용이하겠네요.

2021-04-27 12:55 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/main/MainActivity.kt
> +        btnSearch.setOnClickListener(View.OnClickListener { startActivity(Intent(this@MainActivity, SearchActivity::class.java)) })
네네 딱히 어떤걸로 해도 상관없는 취향의 영역이긴 합니다.

2021-04-28 05:41 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                .subscribe())
Activity마다 rx를 추가하다보니 SearchActivity에서도 rx를 추가했습니다. 해당 코드 삭제했습니다.

2021-04-28 05:50 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +        startActivity(intent)
```
    override fun onItemClick(repository: GithubRepoDto) {
        val intent = saveSearchKeyword(repository)
        goToRepositoryActivity(intent)
    }

    private fun saveSearchKeyword(repository: GithubRepoDto): Intent {
        return Intent(this, RepositoryActivity::class.java).apply {
            putExtra(RepositoryActivity.KEY_USER_LOGIN, repository.owner.login)
            putExtra(RepositoryActivity.KEY_REPO_NAME, repository.name)
        }
    }
    
    private fun goToRepositoryActivity(intent: Intent) {
        startActivity(intent)
    }
```
로 수정하였습니다.

2021-04-28 05:52 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                    }
`   adapter.clearResults()`로 수정하였습니다.

2021-04-28 05:53 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchActivity.kt
> +                    }
`adapter.updateItem(items)`로 수정하였습니다.

2021-04-28 07:14 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +        items[position].let { repo ->
KobaTodo을 참고하여 수정하였습니다. bind 메소드를 ViewHoder에 정의하고, onBindViewHolder에 `  holder.bind(items[position])`한 줄로 바꾸었습니다.

2021-04-28 07:26 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +                setOnClickListener {
item을 생성자로 넘겨서 리스터를 장착했습니다. 중요한건 onViewHolderBind에서 setClickListener를 해주지 않는다군요.
리사이클러뷰가 스크롤되고 업데이트될때마다 setClickListener를 매번 호출할 것 같군요.

2021-04-28 07:41 UTC, koba0909 commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/search/SearchAdapter.kt
> +                setOnClickListener {
맞아요 클릭리스너를 불필요하게 계속 호출하게 됩니다

2021-04-28 07:43 UTC, koba0909 commented
클릭리스너  rx 로 전환 및 레이아웃 수정은 추후에 진행해주세요~

2021-04-28 07:44 UTC, merged

2021-04-28 07:48 UTC, Lee-cg commented on lennonFolder/lennon-github-serach/simple-github/src/main/kotlin/com/androidhuman/example/simplegithub/ui/signin/SignInActivity.kt
> +        val uri = intent.data ?: throw IllegalArgumentException("No data exists")
try, catch문으로 감쌌고, 예외가 발생하면 해당 Activity를 finish() 시켰습니다.