Feature/hoon
koba0909/AndroidStudy pull request #7
Opened 2021-04-06 09:06 UTC by Junghun0

훈 - 검색 기능 작업완료했습니다.

2021-04-06 11:33 UTC, koba0909 requested changes
확인부탁드립니다~

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/MainActivity.kt
> +        viewModel = ViewModelProvider(this, ViewModelProvider.NewInstanceFactory()).get(MainViewModel::class.java)
ViewModel ktx를 사용하면 더 간편하게 선언 가능합니다~

[https://developer.android.com/kotlin/ktx?hl=ko](https://developer.android.com/kotlin/ktx?hl=ko)

```
val viewModel by viewModels<MainViewModel>()
```

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/MainActivity.kt
> +        binding = ActivityMainBinding.inflate(layoutInflater)
ViewModel을 ktx로 선언했으면 아래와 같이 별도의 초기화 없이 수정 가능합니다~
```suggestion
setContentView(binding.root)
```

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +    private lateinit var adapter: SearchAdapter
by lazy로 선언 가능해보여요~
SearchAdapter선언시에 context를 넘기는 이유가 있을까요?

adapter란 네이밍은 불분명하니 searchAdapter로 변경 추천드립니다~

```suggestion
private var searchAdapter by lazy { SearchAdapter() }
```

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        viewModel = ViewModelProvider(this, SearchViewModelFactory(SearchRepoUseCase(GithubSearchRepoImpl(GithubServiceBuilder))))
선언부에서 초기화 가능해요~
KobaTodo/TodoFragment에서 viewModel 초기화한거 참고하시면 됩니다~

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        setContentView(view)
```suggestion
setContentView(binding.root)
```

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +    private fun initAdapter() {
initAdapter에서 adapter를 초기화 하는 역할도 하고 뷰모델의 라이브데이터를 옵저빙하는 역할도 해주고 있네요  
CleanCode에 따르면 하나의 함수에선 하나의 역할만 하는게 추후 의도치 않은 사이드 이슈를 줄일 수 있다고 합니다~ 

어댑터 초기화와 라이브데이터 옵저빙하는걸 분리시키는걸 추천드립니다~

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        binding.searchRecyclerView.adapter = adapter
```suggestion
binding.searchRecyclerView.adapter.apply {
adapter = searchAdapter
addItemDecoration(DividerItemDecoration(this, LinearLayoutManager.VERTICAL)
}
```

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +            viewModel.showProgress(false, binding.searchProgress, binding.searchRecyclerView)
데이터 리스트를 가져오고 나서 showProgress를 해주기 보단 데이터를 요청한 시점에서 부터 보여줘야해요. 네트워크가 딜레이 되는 시간이 가장 길테니까요~

보통 뷰모델쪽에 요청하는 부분에서 doOnSubject를 달아주고 progress를 위한 liveData에 progress를 보여줘야 하는지 넘겨줍니다~

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchViewModel.kt
> +    fun showProgress(isLoading: Boolean, progressBar: ProgressBar, recyclerView: RecyclerView) {
showProgress는 굳이 뷰모델에서 처리해야할 필요 없어보여요~

isLoding 라이브 데이터를 만들고 fragment에서 showProgress해주는게 좋아보입니다~

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/res/layout/search_result_item.xml
> +        app:layout_constraintStart_toEndOf="@+id/repo_thumbnail_imgView"
@+id는 id 리소스를 추가하게 되서 아래와 같이 수정이 되야 해요~

```suggestion
app:layout_constraintStart_toEndOf="@id/repo_thumbnail_imgView"
```

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchAdapter.kt
> +            binding.repoLanguageTextView.text = data.language
with 스코프로 binding을 묶어주면 좀더 가독성이 좋을거 같아요~

```
with(binding) {
repoLanguageTextView.text = data.language
...
}
```

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        val searchView = menu?.findItem(R.id.action_search)?.actionView as SearchView
as?로 캐스팅해서 안정성 가져가는게 좋아보여요~

2021-04-06 11:33 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        searchView.setOnQueryTextListener(object: SearchView.OnQueryTextListener {
as?로 수정했다면 아래와 같이 수정해주세요~
searchView?.setOnQueryTextListener(object: SearchView.OnQueryTextListener {

2021-04-06 13:33 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/MainActivity.kt
> +        viewModel = ViewModelProvider(this, ViewModelProvider.NewInstanceFactory()).get(MainViewModel::class.java)
수정완료했습니다 👍

2021-04-06 13:34 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/MainActivity.kt
> +        binding = ActivityMainBinding.inflate(layoutInflater)
수정완료했습니다 👍

2021-04-06 13:35 UTC, Junghun0 commented
리뷰 해주신부분 수정완료했습니다~ 수고많으셨어요

2021-04-07 11:36 UTC, koba0909 reviewed
추가로 확인해주세요~

2021-04-07 11:36 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +            viewModel.showProgress(false)
여기서 뷰모델로 shoProgress(false)넘기는 이유가 있을까요?

뷰모델 -> 액티비티 -> 뷰모델 -> 액티비티 이렇게 핑퐁될 필요가 없을거같아요~

2021-04-07 11:36 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchAdapter.kt
> +        set(value) {
저도 todo 예시 만들때 이렇게 처리했는데 
훈 혹시 diffUtil사용해 본적 있나요? 이번 기회에 diffUtil에 대해서 공부해보는것도 좋을거 같아요~

[https://proandroiddev.com/recyclerview-antipatterns-8af3feeeccc7](https://proandroiddev.com/recyclerview-antipatterns-8af3feeeccc7)

- 리사이클러뷰 안티패턴에 관한건데 마지막에 diffUtil을 사용해야 하는 이유가 있어서 첨부합니다~

2021-04-15 10:50 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +    private lateinit var adapter: SearchAdapter
수정완료했습니다 👍

2021-04-15 10:50 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        viewModel = ViewModelProvider(this, SearchViewModelFactory(SearchRepoUseCase(GithubSearchRepoImpl(GithubServiceBuilder))))
수정완료했습니다 👍

2021-04-15 10:50 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        setContentView(view)
수정완료했습니다 👍

2021-04-15 10:51 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +    private fun initAdapter() {
수정완료했습니다 👍

2021-04-15 10:51 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        binding.searchRecyclerView.adapter = adapter
수정완료했습니다 👍

2021-04-15 10:51 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +            viewModel.showProgress(false, binding.searchProgress, binding.searchRecyclerView)
수정완료했습니다 👍

2021-04-15 10:51 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchViewModel.kt
> +    fun showProgress(isLoading: Boolean, progressBar: ProgressBar, recyclerView: RecyclerView) {
수정완료했습니다 👍

2021-04-15 10:53 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/res/layout/search_result_item.xml
> +        app:layout_constraintStart_toEndOf="@+id/repo_thumbnail_imgView"
몰랐던 부분인대 지적 감사합니다~ 수정완료했습니다 👍

2021-04-15 10:54 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchAdapter.kt
> +            binding.repoLanguageTextView.text = data.language
수정완료했습니다 👍

2021-04-15 10:55 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        val searchView = menu?.findItem(R.id.action_search)?.actionView as SearchView
수정완료했습니다 👍

2021-04-15 10:55 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +        searchView.setOnQueryTextListener(object: SearchView.OnQueryTextListener {
수정완료했습니다 👍

2021-04-15 10:58 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/SearchActivity.kt
> +            viewModel.showProgress(false)
말씀하신 것처럼 액티비티와 뷰모델에서 불필요하게 양쪽에서 로딩상태에 대해 관여하고 있었네요.
뷰모델에서 Rx 부분에서 로딩상태 처리하였습니다.
수정완료했습니다~ 👍

2021-04-15 11:03 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchAdapter.kt
> +        set(value) {
넵 자료 감사합니다~ 제안해주신대로 diffUtil 을 사용하여 SearchAdapter - SearchViewHolder 수정하였습니다.

2021-04-15 11:04 UTC, Junghun0 commented
리뷰 주신 내용 수정 및 레포 세부정보 나타내는 화면까지 구현 완료 하였습니다~😃

2021-04-16 01:57 UTC, koba0909 reviewed
이거 하나만 더 고쳐주세요~

2021-04-16 01:57 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchViewHolder.kt
> +            }
bind안에서 클릭리스너를 set 해주고 있네요. 이는 리스트 성능저하의 요소입니다.

adapterPosition을 활용해서 뷰홀더를 init 하는 부분이나 생성할때 클릭리스너를 set 해주세요.

2021-04-16 02:32 UTC, koba0909 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/DetailFragment.kt
> +        }
repo가 nullable 이라서 ?: 을 활용해서 null 일때의 값을 넣어 주거나

해당 fragment 를 종료시키는 처리가 들어가는게 좋을거 같아요.

2021-04-22 12:53 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/DetailFragment.kt
> +        }
이 부분은 Rx에서 받는 데이터들 중에 클릭한 아이템을 DetailFragment 에 던져서 처리하는 부분이라서
굳이 Repo 를 nullable 한 타입으로 선언할 필요가 없어보여서 ? 제거하여 수정했습니다~

2021-04-22 12:54 UTC, Junghun0 commented on Hoon/AndroidStudy_Hoon/app/src/main/java/com/study/androidstudy_hoon/presenter/search/SearchViewHolder.kt
> +            }
말씀해주신대로 Holder 한테 Adapter 를 넘겨주어서 Holder init 블록안에서 리스너 등록 처리 하도록 수정하였습니다~

2021-04-22 12:54 UTC, Junghun0 reviewed
남아있던 Room 기능 추가 완료하였고 위에 코멘트 주신부분도 추가적으로 수정하였습니다.

2021-04-26 01:36 UTC, koba0909 approved these changes

2021-04-26 01:37 UTC, merged